### ISSUE TITLE
mafengwo_spider Error 521

### ISSUE THREAD

**Issue by sun254667307** [yuvenhol/dataharvest#1]
```
from src.dataharvest.spider import AutoSpider

url = "https://www.mafengwo.cn/i/24424554.html"
auto_spider = AutoSpider()
doc = auto_spider.crawl(url)
with open('text.txt', 'a+') as f:
    f.write(str(doc))
```

Traceback (most recent call last):
  File "test.py", line 6, in <module>
    doc = auto_spider.crawl(url)
  File "/home/dataharvest/src/dataharvest/spider/spider.py", line 25, in crawl
    return spider.crawl(url, config)
  File "/home/dataharvest/src/dataharvest/spider/mafengwo_spider.py", line 70, in crawl
    final_content = handle_final_content(third_resp)
  File "/home/dataharvest/src/dataharvest/spider/mafengwo_spider.py", line 158, in handle_final_content
    third_resp.raise_for_status()
  File "/opt/conda/envs/wenlv/lib/python3.8/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '521 Connection Reset by Origin' for url 'https://www.mafengwo.cn/i/24424554.html'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/521

**Comment by yuvenhol** [comment]
我这里测试是没有问题的，推荐你排查一下网络，有没有使用vpn等代理工具。如果访问非常快会触发马蜂窝的反扒机制，需要实现一下代理类。
![202407101836467](https://github.com/yuvenhol/dataharvest/assets/48517852/70315699-1a1b-4bb8-ab2a-1a172e3f6b20)

**Comment by sun254667307** [comment]
> 我这里测试是没有问题的，推荐你排查一下网络，有没有使用vpn等代理工具。如果访问非常快会触发马蜂窝的反扒机制，需要实现一下代理类。 ![202407101836467](https://private-user-images.githubusercontent.com/48517852/347368029-70315699-1a1b-4bb8-ab2a-1a172e3f6b20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTIxNTIsIm5iZiI6MTcyMDYxMTg1MiwicGF0aCI6Ii80ODUxNzg1Mi8zNDczNjgwMjktNzAzMTU2OTktMWExYi00YmI4LWFiMmEtMWExNzJlM2Y2YjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDExNDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczODRjN2NlMGY4ODkzZGI0YjVkMDZkMjg3NGY1ZTFhY2M2MjVjYzczMGNmYzE3ZDE1NGM1ZDM3NTlmOWMwYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.akw2ps2C3_SX1kjyycEQqru6qSapemEAcqdm6sA18ZI)

`
class MaFengWoSpider(BaseSpider):
    def __init__(self, config: Optional[SpiderConfig] = None):
        self.client = httpx.Client(**BaseSpider.convert_2_httpx_client_arg(config))
        self.a_client = httpx.AsyncClient(**BaseSpider.convert_2_httpx_client_arg(config))
        self._config = self._merge_config(config)

        if not self._config.headers:
            # for linux
            self._config.headers = {
                "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11",
            }
`

**Comment by yuvenhol** [comment]
> ```
> class MaFengWoSpider(BaseSpider):
>     def __init__(self, config: Optional[SpiderConfig] = None):
>         self.client = httpx.Client(**BaseSpider.convert_2_httpx_client_arg(config))
>         self.a_client = httpx.AsyncClient(**BaseSpider.convert_2_httpx_client_arg(config))
>         self._config = self._merge_config(config)
> 
>         if not self._config.headers:
>             # for linux
>             self._config.headers = {
>                 "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.64 Safari/537.11",
>             }
> ```
应该和user-agent没有关系。
